# 07 — Remote Access Tools

## What Was Built and Why

For this section of the lab, I tested 3 different remote access methods, each representing a distinct access model with its own permission system.

**Remote Desktop (RDP)**
RDP provides full interactive control of the remote machine's desktop, which provides an effective way to access another computer from anywhere without needing the person at the other end to be present or do anything. For this section, access was granted at the group level through Group Policy Preferences, updating the local Remote Desktop Users group on target machines to include `SG-IT`. This started as a manual, per-machine local group edit, which was later replaced by the GPO-based version once working — the manual entry was then removed, so the GPO is now the only path granting this access.

![Helpdesk RDP session into Desktop2](./screenshots/rdp-session.png)

**Remote Registry**

Remote Registry lets an admin view and edit a remote machine's Windows Registry directly over the network, without a desktop session and without any visible windows on the target machine, which makes it suited to low-level configuration or inventory tasks. To test this out, I connected to Desktop2's registry from the `Helpdesk` account. But unlike RDP, registry access isn't controlled by a single group membership; it requires explicit permission on the `winreg` key itself, separate from being a local administrator. In order to get it to work, I also had to enable **File and Printer Sharing** inbound firewall rules, which are disabled by default and block the connection regardless of registry permission being correctly set.

![winreg permissions granting access to the helpdesk principal](./screenshots/winreg-permissions.png)

**Remote Assistance**

This was used for a scenario requiring a live walkthrough rather than a silent fix. The end user would generate an invitation, and the person assisting would connect using the invitation and then, if required, be granted control by getting the user to accept. The invitation file was retrieved using an administrative share rather than an email transfer.
![Remote Assistance session in progress](./screenshots/remote-assistance-session.png)

---

## Access Model Comparison

| Tool | Who grants access | Consent required from end user? | Typical use |
|---|---|---|---|
| RDP | Group membership (Remote Desktop Users) | No | Backend admin work, no need for the user to be present |
| Remote Registry | Explicit `winreg` permission + firewall rule | No | Low-level configuration/inventory, rarely used due to lateral-movement risk |
| Remote Assistance | Invitation generated by the user | Yes, explicitly | Walking a user through a fix live, user stays in control throughout |

---

## Key Lessons Learned

- **"Remote access" isn't one permission system.** RDP, Remote Registry, and file/printer sharing are each gated by their own distinct mechanism, and none of them imply the others. Being able to RDP into a machine doesn't mean Remote Registry will also work, since that depends on separate `winreg` permissions and firewall rules entirely.
- **Firewall rules for File and Printer Sharing are disabled by default** on a fresh domain-joined machine, and this silently blocks Remote Registry even when the `winreg` permission itself is correctly configured which is easy to misdiagnose as a permissions problem when it's actually a firewall one.
- **Remote Registry is worth knowing how to use, and also worth knowing why it's often restricted.** It's flagged in hardening guides as a lateral-movement and reconnaissance risk, which is why many real environments disable it entirely except on specific, tightly scoped machines.
- **Consent-based access (Remote Assistance) and administrative access (RDP, Remote Registry) solve different problems.** Remote Assistance is the right tool when the goal is for the user to see and understand the fix, not just have it applied.
